app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from app.models import User, Role, Book, Tag, Level, Post
from flask import render_template, flash, redirect, url_for, request, current_app
from flask_login import current_user


@bp.route('/', methods=['GET', 'POST'])
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.list_books', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.list_books', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('main/news.html', title=('posts'), posts=posts.items, 
        next_url=next_url, prev_url=prev_url, page=page)

@bp.route('/news', methods=['GET', 'POST'])
def news():
    return render_template('main/news.html', title=('news'))

@bp.route('/articles', methods=['GET', 'POST'])
def articles():
    return render_template('main/articles.html', title=('articles'))

@bp.route('/books', methods=['GET'])
def list_books():
    page = request.args.get('page', 1, type=int)
    books = Book.query.order_by(Book.year.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.list_books', page=books.next_num) \
        if books.has_next else None
    prev_url = url_for('main.list_books', page=books.prev_num) \
        if books.has_prev else None
    return render_template('main/books.html', title=('books'), books=books.items, 
        next_url=next_url, prev_url=prev_url, page=page)

@bp.route('/about', methods=['GET', 'POST'])
def about():
    return render_template('main/about.html', title=('about'))

@bp.route('/faq', methods=['GET', 'POST'])
def faq():
    return render_template('main/faq.html', title=('faq'))

@bp.route('/more/<int:id>', methods=['GET'])
def more(id):
    book = Book.query.filter_by(id=id).first_or_404()
    # if not current_user.is_authenticated:
    #     redirect('.admin.index')
    return render_template('main/more.html', title=('about book'), book=book)

@bp.route('/article/<int:id>', methods=['GET'])
def article(id):
    post = Post.query.filter_by(id=id).first_or_404()
    return render_template('main/article.html', post=post)

app/templates/main/about.html
{% extends 'mybase.html' %}
{% block content %}
about
{% endblock %}

app/templates/main/article.html
{% extends 'mybase.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div data-spy="scroll" data-target="#navbar-example3" data-offset="0">
            <h3 id="item-1">{{ post.title }}</h3>
            <p>{{ post.text|safe }}</p>
            <h5 id="item-1-1">Дата записи:</h5>
            <p>{{ post.timestamp }}</p>
          </div>
    </div>
</div>

{% endblock %}

app/templates/main/books.html
{% extends 'mybase.html' %}
{% block content %}

{% for book in books %}
<div class="card">
    <!-- <div class="card-header">
      Featured
    </div> -->
    <div class="card-body">
      <h5 class="card-title">{{ book.name }}</h5>
      <p class="card-text">{{ book.description[:50] }}</p>
      <a href="{{ url_for('main.more', id=book.id) }}" class="btn btn-primary">More..</a>
    </div>
</div>
{%endfor%}

<nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item{% if not prev_url %} disabled{% endif %}">
        <a class="page-link" href="{{ prev_url or '#' }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
      <li class="page-item"><a class="page-link">{{ page }}</a></li>
      <li class="page-item{% if not next_url %} disabled{% endif %}">
        <a class="page-link" href="{{ next_url or '#' }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    </ul>
</nav>

{% endblock %}

app/templates/main/faq.html
{% extends 'mybase.html' %}
{% block content %}
faq
{% endblock %}

app/templates/main/more.html
{% extends 'mybase.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div data-spy="scroll" data-target="#navbar-example3" data-offset="0">
            <h3 id="item-1">{{ book.name }}</h3>
            <p>{{ book.description }}</p>
            <h5 id="item-1-1">Год издания</h5>
            <p>{{ book.year }}</p>
            <h5 id="item-1-2">Издательство</h5>
            <p>{{ book.publisher }}</p>
            <h5 id="item-3-1"></h5>
            <a href="{{ url_for('download_blob', id=book.id) }}" class="btn btn-primary">Download</a>
          </div>
    </div>
</div>

{% endblock %}

app/templates/main/news.html
{% extends 'mybase.html' %}
{% block content %}

<div data-bs-spy="scroll" data-bs-target="#navbar-example3" data-bs-smooth-scroll="true" tabindex="0">
{% for post in posts%}
<div class="card">
    <!-- <div class="card-header">
      Featured
    </div> -->
    <div class="item-1">
      <h5 class="item-1-1"><a href="{{ url_for('main.article', id=post.id) }}">{{ post.title }}</a></h5>
      <p class="card-text">{{ post.text[:150]}}</p>
    </div>
</div>
{%endfor%}
</div>
<nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item{% if not prev_url %} disabled{% endif %}">
        <a class="page-link" href="{{ prev_url or '#' }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
      <li class="page-item"><a class="page-link">{{ page }}</a></li>
      <li class="page-item{% if not next_url %} disabled{% endif %}">
        <a class="page-link" href="{{ next_url or '#' }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    </ul>
  </nav>
{% endblock %}